config/routes.rb
Depot::Application.routes.draw do
  
  
  resources :orders
  
  resources :customers

  get 'admin' => 'admin#index'
  
  get 'account' => 'customers#show'
  
  match '/account', :to => 'customers#show'
  
  match'/signup', :to => 'customers#new'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  

  resources :users

  resources :line_items

  resources :carts

  get "store/index"

  resources :products do
    get :who_bought, on: :member
  end
  
   resources :line_items do
    put 'decrease', on: :member
    put 'increase', on: :member
  end

  root to: 'store#index', as: 'store'

end

app/models/customer.rb
require 'mail'
class Customer < ActiveRecord::Base
  include ActiveModel::Validations
  attr_accessible :address, :email, :name, :password, :password_confirmation
  
  has_many :orders
  
  validates :name, presence:true, :length => { :maximum => 50 }
  validates :email, presence:true, :uniqueness => {:case_sensitive => false}, :email => true
  validates :address, presence:true
  validates :password, presence:true, confirmation:true, :length => { :within => 6..40 }
  has_secure_password
  
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  skip_before_filter :authorize, only: [:create, :new]
  
  # GET /customers
  # GET /customers.json
  def index
    if !session[:user_id]
      redirect_to customer_path(session[:customer_id]) , notice: 'Access Denied'
    return
    else
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    if customer_path(session[:customer_id])!=customer_path
      redirect_to customer_path(session[:customer_id]), notice: 'Access denied. Please login to view this account.'
    else
      @customer = Customer.find(params[:id])
      @orders = @customer.orders.paginate page: params[:page], order: 'id desc',
      per_page: 5

      
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new
    @title = "Sign Up"

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
    def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        session[:customer_id] = @customer.id
        format.html { redirect_to new_order_path, method: :get, notice: "Your account was successfully created." }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to customer_path(session[:customer_id]), notice: 'Your account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<div class="depot_form">

<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<fieldset>
  <div class="field">
    <%= f.label :name, 'Full Name' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address, :rows=>6 %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password, 'Password' %><br />
    <%= f.password_field :password, size: 40 %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, 'Confirm Password' %><br />
    <%= f.password_field :password_confirmation, size: 40 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</fieldset>
<% end %>
</div>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Cancel', customer_path(session[:customer_id]) %>

app/views/customers/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1>Listing customers</h1>

<table>
  <tr>
  	<th>ID</th>
    <th>Name</th>
    <th>Address</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @customers.each do |customer| %>
  <tr>
  	
   	<td><%= customer.id %></td>
    <td><%= customer.name %></td>
    <td><%= customer.address %></td>
    <td><%= customer.email %></td>
    <td><%= link_to 'Show', customer %></td>
    <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
    <td><%= link_to 'Destroy', customer, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />
<% if session[:customer_id] %>
<%= button_to 'Logout', logout_path, method: :delete %>
<% end %>

app/views/customers/new.html.erb
<h3>Please register to place your order</h3>
<p>If you are already a customer, please use the link on the left to log in.</p>

<%= render 'form' %>

<%= link_to 'Back', store_url %>

app/views/customers/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1> Welcome, <%= @customer.name %></h1>

<p>
  <b>Address:</b>
  <%= @customer.address %>
</p>

<p>
  <b>Email:</b>
  <%= @customer.email %>
</p>

<%= link_to 'Change Your Details', edit_customer_path(@customer), method: :get %>

<br />

<h3>Your Orders:</h3>
<table class="order-items">
	<th>Date</th>
	<th>Order No.</th>
	<th>View Order</th>
	<% @orders.each do |order| %>
		<tr>
			<td><%= order.created_at.strftime("%d %b. %Y") %></td>
			<td><%= order.id %></td>
			<td><%= link_to 'Show',  order_path(order) %></td>
		</tr>
	<% end %>	
</table>

<p><%= will_paginate @orders %></p>