config/routes.rb
Depot::Application.routes.draw do
  
  
  resources :orders
  
  resources :customers

  get 'admin' => 'admin#index'
  
  get 'account' => 'customers#show'
  
  match '/account', :to => 'customers#show'
  
  match'/signup', :to => 'customers#new'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  

  resources :users

  resources :line_items

  resources :carts

  get "store/index"

  resources :products do
    get :who_bought, on: :member
  end
  
   resources :line_items do
    put 'decrease', on: :member
    put 'increase', on: :member
  end

  root to: 'store#index', as: 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
	<div id="banner">
		<%= image_tag("logo.png") %>
		<%= @page_title || "Pragmatic Bookshelf" %>
	</div>

	<div id="columns">
		<div id="side">
			<% if @cart %>
				<%= hidden_div_if(@cart.line_items.empty?, id:'cart') do %>
					<%= render @cart %>
				<% end %>			
			<% end %>
			<ul>
				<li><a href="../">Home</a></li>
				<li><a href="../about.html">About</a></li>
				<li><a href="../info.html">Information</a></li>
				<li><a href="../contact.html">Contact Us</a></li>
				<% if session[:customer_id] %>
				<br />
				<li><%= button_to 'My Account', customer_path(session[:customer_id]), method: :get %></li>
				<% end %>
			</ul>
			<% if !session[:user_id] && !session[:customer_id] %>
			<%= button_to 'Login', login_path %>
			<% end %>
			<% if session[:user_id] || session[:customer_id] %>
			<%= button_to 'Logout', logout_path, method: :delete %>
			<% end %>
			<% if session[:user_id] %>
				<ul>
					<li><%= link_to 'Orders', orders_path %></li>
					<li><%= link_to 'Products', products_path %></li>
					<li><%= link_to 'Users', users_path %></li>
				</ul>
			<% end %>
		</div>

		<div id="main">
			<%= yield %>
		</div>
	</div>
</body>
</html>